### ISSUE TITLE
Download mobile app issue

### ISSUE THREAD

**Issue by H7-25** [kiwiirc/plugin-conference#22]
If you try to open a conference with an ios device (not tested with android) you can see both download mobile app link and continue to the app link . Clicking on that doesn't work.
I think the issue is related to jitsi-meet opened into the mediaviewer , opening jitsi-meet directly don't have this issue

**Comment by H7-25** [comment]
I think the problem is related to the fact that jitisi external api open an iframe into another iframe (mediaviewer iframe)

**Comment by srmcgann** [comment]
This has been fixed by adding target="_blank" to the jitsi source.
