### ISSUE TITLE
[Feature] Output conference URL when starting video call in channel

### ISSUE THREAD

**Issue by TheMythPT** [kiwiirc/plugin-conference#29]
Right now, when using public Jitsi servers in the plugin, for those not using KiwiIRC we just receive a message in the channel saying `* $nick has joined the conference.`
For some people that use more often the mobile than the PC, would be nice to be able to see (probably) the actual link of the conference, so we could join via Jitsi mobile app.
I know this might raise some security issues, and therefore that could probably have an option to turn `on/off` in the config.json file.

**Comment by Shillos** [comment]
Would be nice with a short link like bit.ly or similar so the url isn't too long!

**Comment by srmcgann** [comment]
Checking into this..

**Comment by prawnsalad** [comment]
@srmcgann the link should be sent for other clients to see. Sent via the PRIVMSG, not shown in the kiwi client as that's pointless there since it already has a button.
