### ISSUE TITLE
Found main.js 

### ISSUE THREAD

**Issue by djlolito** [kiwiirc/plugin-conference#31]
Good morning, I'm trying to install the plugin, when I do the payment of the yarn and yarn build, I go to the dist folder, but there is no main.js file, attached paste of the process.
yarn run v1.12.3
$ webpack
Hash: 871c68fb64e033289bf0
Version: webpack 4.16.2
Time: 1206ms
Built at: 12/11/2018 12:54:09 PM
                       Asset      Size  Chunks             Chunk Names
    plugin-conference.min.js  60.6 KiB    main  [emitted]  main
plugin-conference.min.js.map    84 KiB    main  [emitted]  main
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {main} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {main} [built]
[./plugin-conference.js] 14.6 KiB {main} [built]
    + 1 hidden module
Done in 2.40s.
[user@user plugin-conference]# yarn install
yarn install v1.12.3
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.21s.
[user@user plugin-conference]# cd dist
[user@user dist]# ls
plugin-conference.min.js  plugin-conference.min.js.map

**Comment by ItsOnlyBinary** [comment]
The readme did not get updated when the file names changed, copy the `plugin-conference.min.js` and  `plugin-conference.min.js.map` files to your plugins folder. Add plugin-conference.min.js to your client.json
