### ISSUE TITLE
Link send failed

### ISSUE THREAD

**Issue by djlolito** [kiwiirc/plugin-conference#35]
I have detected a bug when making the call between two users who enter by kiwi.

I enter from 2 browsers to perform the test.
I connect to the network and I give it to call the other user, to me as the sender if I get the script of the call, the recipient is opened a private blank.
Nothing appears to him, however he gives the phone and accepts the call.

 I use the last commit of plugin-conference

**Comment by srmcgann** [comment]
Hi @djlolito. There is a known issue involving message tags that will cause this, if I am understanding you correctly. That is, any network that does not support message tags, will cause the join button to fail. I'm guessing that's what's happening here. What network are you testing on? I will check it out. Thanks for using the plugin!

**Comment by djlolito** [comment]
http://webchat.kaosnet.es:8080

if you open 2 tabs and you send the call invitation you will see that a private blank is opened, the message of the invitation to the call does not appear.

Thx!

**Comment by srmcgann** [comment]
I get G-Lined right after connecting.

**Comment by djlolito** [comment]
> I get G-Lined right after connecting.

please try now

**Comment by srmcgann** [comment]
@djlolito, I've figured it out. There was a change in kiwi's core on Dec 18, 2018 that affects the way messages are rendered. This caused a bit of trouble with the conferencing plugin until we fixed it to work with Kiwi's current version. So, short answer, update Kiwi and the button issue will be fixed. I'm closing this issue for now. Please let me know if there is anything.
