### ISSUE TITLE
Compilation impossible.

### ISSUE THREAD

**Issue by a-b-cd** [kiwiirc/plugin-conference#39]
hello, after cloning your plugin-conference directory, I run yarn && yarn build :

> : ~ / plugin-conference # yarn && yarn build
> ERROR: There are no scenarios; must have at least one.
> : ~ / Plugin-conference #

so i search a little by myself and run: yarn plugin-conference.js

> : ~/plugin-conference# yarn plugin-conference.js
> ERROR: Syntax error: unknown step:             // 5. If n ≥ 0, then

so I tried to delete all comments (//)

> : ~/plugin-conference# yarn plugin-conference.js
> ERROR: Syntax error: unknown step:             let k = Math.max(n >= 0 ? n : len - Math.abs(n), 0);

thank you in advance to all help me to fix that :)

**Comment by ItsOnlyBinary** [comment]
Im suspecting this is due to an old version of nodejs or yarn

**Comment by vith** [comment]
The `yarn` you're running isn't the javascript package manager, it's something unrelated.

See https://github.com/yarnpkg/yarn/issues/2821 and https://yarnpkg.com/lang/en/docs/install/

**Comment by a-b-cd** [comment]
> The `yarn` you're running isn't the javascript package manager, it's something unrelated.
> 
> See [yarnpkg/yarn#2821](https://github.com/yarnpkg/yarn/issues/2821) and https://yarnpkg.com/lang/en/docs/install/

thank you ! but after build this how to configure please ? i have placed the config in my kiwiirc .conf but not working :/

**Comment by ItsOnlyBinary** [comment]
new kiwiirc uses config.json, .conf sounds like your trying to use this plugin on old kiwiirc which will not work.

https://github.com/kiwiirc/kiwiirc && https://github.com/kiwiirc/webircgateway
Feel free to drop in for live support @ https://kiwiirc.com/nextclient/irc.freenode.net/#kiwiirc
