### ISSUE TITLE
isn't working at the moment 

### ISSUE THREAD

**Issue by bexyboo** [kiwiirc/plugin-conference#47]
SyntaxError: expected expression, got '<'
external_api.min.js:1
TypeError: iframe.contentWindow.JitsiMeetExternalAPI is not a constructorplugin-conference.min.js line 21 > eval:471:27
    _ref3 webpack:///./plugin-conference.js?:471

**Comment by prawnsalad** [comment]
This looks like the URL to your jitsi is incorrect. Have you got a link to your kiwi instance where this is breaking?

**Comment by bexyboo** [comment]
i'll try a different url ty its on https://kiwi.anxiety.live

**Comment by bexyboo** [comment]
i figured out why it wasn't working , the plugin is searching for myjitsidomain/external_api.min.js and jitsi meet uses myjitsidomain/external_api.js in its nginx setup. i added the .min.js filename to the nginx setup and it works now :)
