### ISSUE TITLE
Conference

### ISSUE THREAD

**Issue by elvis72500** [kiwiirc/plugin-conference#49]
J’ai besoin d’aide pour le plugin conférence de kiwiirc merci

**Comment by prawnsalad** [comment]
Translated: I need help with the kiwiirc conference plugin thank you

You should say what you are trying to do, what is happening, and what you expected it to do.

**Comment by elvis72500** [comment]
You should say what you are trying to do, what is happening, and what you expected it to do.

**Comment by elvis72500** [comment]
???
