### ISSUE TITLE
 'Join now!' button is never displayed 

### ISSUE THREAD

**Issue by Ircgo** [kiwiirc/plugin-conference#87]
When other user invites you to the conference call, 'X is inviting you to a private call.' is displayed, but there is no 'Join now!' (conference.joinButtonText) button.

**Comment by ItsOnlyBinary** [comment]
My guess is your using unrealircd and it does not allow client to client message tags by default

https://github.com/ValwareIRC/valware-unrealircd-mods/tree/main/mtag-manager

`+kiwiirc.com/conference;`

**Comment by Ircgo** [comment]
Thankyou [ItsOnlyBinary](https://github.com/ItsOnlyBinary)

**Comment by ItsOnlyBinary** [comment]
I assume this solved your issue, reply here if not and i will be notified :)
